export const trackingStatusEnums = {
  MOVING: 'MOVING',
  PARKED: 'PARKED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  DEVICE_MALFUNCTIONING: 'DEVICE_MALFUNCTIONING',
  NO_RESPONSE: 'NO_RESPONSE',
  OFF_ROAD: 'OFF_ROAD',
  OUT_OF_SERVICE: 'OUT_OF_SERVICE',
  ALL: 'ALL',
};